"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from datetime import timedelta
from pathlib import Path
import os

import dj_database_url
from dotenv import load_dotenv

from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/
def env_bool(name, default=False):

    value = os.getenv(name)

    if value is None:
        return default

    return value.lower() in {
        "1", "true", "yes", "on"
    }
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
DEBUG = env_bool("DEBUG", False)
if not SECRET_KEY:

    if DEBUG:
        SECRET_KEY = "dev-only-change-me"

    else:
        raise ImproperlyConfigured(
            "SECRET_KEY must be set."
        )
# SECURITY WARNING: don't run with debug turned on in production!


ALLOWED_HOSTS = [

    host.strip()

    for host in os.getenv(
        "ALLOWED_HOSTS",
        "localhost,127.0.0.1"
    ).split(",")

    if host.strip()
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "corsheaders",          # <-- ADD THIS

    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "user",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",   # <-- FIRST

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

USE_POSTGIS = env_bool("USE_POSTGIS", False)

if USE_POSTGIS and DATABASES["default"]["ENGINE"] == (
    "django.db.backends.postgresql"
):

    DATABASES["default"]["ENGINE"] = (
        "django.contrib.gis.db.backends.postgis"
    )


if USE_POSTGIS and DATABASES["default"]["ENGINE"] != (
    "django.contrib.gis.db.backends.postgis"
):

    raise ImproperlyConfigured(
        "DATABASE_URL must point to PostGIS."
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_USER_MODEL = "user.User"

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "noreply@example.com")
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "25"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", False)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {

    "DEFAULT_AUTHENTICATION_CLASSES": (

        "rest_framework_simplejwt.authentication."
        "JWTAuthentication",
    ),

    "DEFAULT_PERMISSION_CLASSES": (

        "rest_framework.permissions.AllowAny",
    ),

    "DEFAULT_THROTTLE_CLASSES": (

        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
        "rest_framework.throttling.ScopedRateThrottle",
    ),

    "DEFAULT_THROTTLE_RATES": {

        "anon": os.getenv("ANON_THROTTLE_RATE", "60/min"),
        "user": os.getenv("USER_THROTTLE_RATE", "120/min"),
        "property_list": os.getenv("PROPERTY_LIST_THROTTLE_RATE", "60/min"),
    },

    "EXCEPTION_HANDLER": "config.exceptions.api_exception_handler",
}


SIMPLE_JWT = {

    "ACCESS_TOKEN_LIFETIME":
    timedelta(
        minutes=int(
            os.getenv("EXPIRE_MINS", "10")
        )
    ),

    "REFRESH_TOKEN_LIFETIME":
    timedelta(days=7),

    "AUTH_HEADER_TYPES":
    ("Bearer",),

    "ALGORITHM":
    os.getenv("ALGORITHM", "HS256"),

    "SIGNING_KEY":
    SECRET_KEY,

    "USER_ID_FIELD":
    "id",

    "USER_ID_CLAIM":
    "user_id",
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]