# Generated by Django 5.2.14 on 2026-08-05 18:39

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_source', models.CharField(choices=[('TEXT', 'Text'), ('OCR', 'OCR')], default='TEXT', max_length=20)),
                ('cleaned_claim', models.TextField(blank=True)),
                ('normalized_claim', models.TextField(blank=True)),
                ('canonical_claim', models.TextField(blank=True)),
                ('fingerprint', models.TextField(blank=True)),
                ('entities', models.JSONField(default=dict)),
                ('keywords', models.JSONField(default=list)),
                ('numbers', models.JSONField(default=list)),
                ('dates', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ExactClaimCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('normalized_claim', models.TextField(unique=True)),
                ('verdict', models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NEI', 'Not Enough Information')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('credibility_score', models.FloatField()),
                ('explanation', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.TextField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=512)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('source_reliability', models.FloatField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='data.claim')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='final_result', serialize=False, to='data.claim')),
                ('verdict', models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NEI', 'Not Enough Information')], max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('credibility_score', models.FloatField()),
                ('llm_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NLIResult',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nli_result', serialize=False, to='data.source')),
                ('supports', models.FloatField()),
                ('contradicts', models.FloatField()),
                ('neutral', models.FloatField()),
                ('label', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SourceEmbedding',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='data.source')),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEmbedding',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='data.claim')),
                ('embedding_vector', pgvector.django.vector.VectorField(dimensions=1024)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding_vector'], m=16, name='claim_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
