# Generated by Django 5.2.14 on 2026-07-25 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_text', models.TextField()),
                ('normalized_claim', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('title', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=512)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('cleaned_text', models.TextField(blank=True)),
                ('source_reliability', models.FloatField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='data.claim')),
            ],
        ),
        migrations.CreateModel(
            name='FinalResult',
            fields=[
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='final_result', serialize=False, to='data.claim')),
                ('credibility_score', models.FloatField()),
                ('confidence_score', models.FloatField()),
                ('llm_explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='embedding', serialize=False, to='data.source')),
                ('embedding_vector', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='NLIResult',
            fields=[
                ('source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nli_result', serialize=False, to='data.source')),
                ('supports', models.FloatField()),
                ('contradicts', models.FloatField()),
                ('neutral', models.FloatField()),
            ],
        ),
    ]
